import React from "react";
import { Layout } from "../../components/Layout";
import { Helmet } from "react-helmet-async";

export const TermCondition = () => {
  return (
    <Layout>
      <Helmet>
        <meta charset="UTF-8" />
        <title>Grow Infinity Realtors | Terms & Conditions</title>
        <meta
          name="description"
          content="Read our Terms & Conditions to understand the rules and regulations governing your use of our services."
        />
        <meta name="robots" content="index, follow" />
        <link
          rel="canonical"
          href={`${process.env.BASE_URL}/terms-and-conditions`}
        />
      </Helmet>
      <div className="privacybanner flex justify-center items-center bg-gray-800 py-12">
        <div className="text-center">
          <h1 className="font-dmsans font-semibold text-white text-4xl capitalize">
            Terms & Conditions
          </h1>
        </div>
      </div>
      <div className="container mx-auto px-6 py-12 text-gray-800 leading-7">
        <h1 className="text-3xl font-bold mb-6 text-center text-gray-900">
          Terms of Use for Grow Infinity Realtors
        </h1>
        <p className="mb-6 text-justify">
          In accordance with the Information Technology Act, 2000, this document
          is an electronic record. Being generated by a computer system, it does
          not require any physical or digital signature. This document is
          published in accordance with the provisions of Rule 3 (1) of the
          Information Technology (Intermediaries Guidelines) Rules, 2011, which
          require the publishing of the rules and regulations, privacy policy,
          and terms of use for access or usage of the website Grow Infinity
          Realtors. The domain name Grow Infinity Realtors is registered under
          the Companies Act, 1956. For the purpose of these Terms of Use,
          wherever the context requires, “You” or “User” shall mean any
          legitimate person who is viewing or browsing the Website and/or has
          agreed to avail the Services provided through the Website by providing
          the required information while registering on the Website. The terms
          “We,” “Us,” and “Our,” used in these Terms shall mean Grow Infinity
          Realtors.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Acceptance of Terms of Use
        </h2>
        <p className="mb-6 text-justify">
          Your use of this Website is governed solely by these Terms of Use
          (“Terms” or “Terms of Use”) and any policies as referenced. Browsing
          the Website or using the services offered through the Website shall be
          taken to mean that You have read and agreed to these Terms of Use,
          which are binding on You, and that You are contracting with Grow
          Infinity Realtors and have undertaken binding obligations with Grow
          Infinity Realtors. By accepting these Terms of Use, whether implicitly
          or explicitly, You also accept and agree to be bound by the Privacy
          Policy available at /privacy-policy, which may be amended from time to
          time. You will be subject to the rules, guidelines, policies, terms,
          and conditions applicable to any service provided by this Website.
          These shall be deemed to be incorporated into this Terms of Use and
          considered part of the Terms.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Modification of Terms/Services
        </h2>
        <p className="mb-6 text-justify">
          We reserve the right to modify the Terms of Use without prior
          permission from You or informing You. It is Your duty to periodically
          check these Terms and stay updated on its requirements. If You
          continue to browse/use the Website following any such changes, this
          will be deemed as consent by You to the amended policies. Grow
          Infinity Realtors reserves the right to withdraw, wholly or in part,
          without assigning any reason, any of the services offered through the
          Website, with or without notice. Grow Infinity Realtors also reserves
          the right to vary the number of leads delivered against listing packs
          from time to time without prior notice of intimation.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Regulation of Website Usage
        </h2>
        <p className="mb-6 text-justify">
          The User agrees and undertakes not to reverse engineer, modify, copy,
          distribute, transmit, display, perform, reproduce, publish, license,
          create derivative works from, transfer, or sell any information or
          software obtained from the Website. You agree not to use the Website
          (including, without limitation, any Services you may obtain through
          your use of the Website): 1. In a manner that violates any local,
          state, national, foreign, or international statute, regulation, rule,
          order, treaty, or other law; 2. To stalk, harass, or harm another
          individual or organization; 3. To impersonate any person or entity or
          otherwise misrepresent your affiliation with a person or entity; 4. To
          interfere with or disrupt the Website or servers or networks connected
          to the Website. Without limiting the foregoing, you may not list or
          sell any prohibited or banned items in the Marketplace. You agree not
          to submit any property descriptions, photographs, financial, contact,
          or other information contained in each Property’s data to the Website
          unless You have acquired all necessary rights and authorizations from
          the owner of such property or the power-of-attorney holder, including
          from the photographer and/or copyright owner of any photographs, to
          publish and advertise the property on the Website. Photographs with
          any watermark are prohibited.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Termination of Registration
        </h2>
        <p className="mb-6 text-justify">
          Without limiting any other remedies, Grow Infinity Realtors may
          terminate your account if (a) you are found or suspected to have
          engaged in fraudulent activity in connection with the use of our
          Services, (b) we believe that you have breached these Terms, or for
          any other reasons deemed fit by Grow Infinity Realtors, with or
          without assigning any reasons/evidence thereof.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Intellectual Property Rights
        </h2>
        <p className="mb-6 text-justify">
          All logos, brands, trademarks, and service marks (“Marks”) appearing
          on the Website are either owned or used under license by Grow Infinity
          Realtors. All rights accruing from the same, statutory or otherwise,
          wholly vest with Grow Infinity Realtors. Access to this Website does
          not confer upon you any license or right to use these Marks, and the
          use of these Marks in any form or manner is strictly prohibited. Any
          violations will constitute an offense under the prevailing laws of
          India. Grow Infinity Realtors respects the Intellectual Property
          Rights of all and will continue to adhere to all applicable laws in
          this respect. In cases where a User is found to be using the Website
          to infringe upon the Intellectual Property Rights of others, Grow
          Infinity Realtors reserves the right to terminate the User’s account
          without any notice.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Disclaimer of Warranties
        </h2>
        <p className="mb-6 text-justify">
          All information and services provided by the Company through the
          Website are provided “as is” and “as available” without warranty of
          any kind, either expressed or implied, including, but not limited to,
          the implied warranties of merchantability, fitness for a particular
          purpose, title, or non-infringement, or arising from a course of
          dealing, usage, or trade practice. Grow Infinity Realtors does not
          warrant that the services offered are free from errors or mistakes.
          Grow Infinity Realtors does not guarantee that defects or limitations
          in the services will be corrected. Additionally, Grow Infinity
          Realtors does not warrant that the services will be available
          continuously. Certain extenuating circumstances may cause service
          interruptions. Grow Infinity Realtors provides no remedies for such
          service interruptions or for any loss of data resulting from using the
          services. Grow Infinity Realtors shall not be responsible for any
          damage of any kind (consequential, direct, incidental, hardware,
          software, or otherwise) due to access, download, or use of content
          from the website. The content of the website may include inaccuracies
          or typographical errors and is frequently updated with reference to
          improvements and corrections without notice.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          No Liability
        </h2>
        <p className="mb-6 text-justify">
          Unless explicitly stated in any part of the Website, we are not
          involved in the actual transactions between buyers and sellers of any
          goods or services, or any users posting information/listings on the
          Website. We have no control over the quality, safety, or legality of
          the items or services advertised, the truth or accuracy of the
          listings, the ability of sellers to sell items, or the ability of
          buyers to purchase items offered through the Website. We cannot
          control whether sellers will complete the sale of items they offer or
          whether buyers will complete the purchase of items they have committed
          to buy. Moreover, there are risks involved in dealing with individuals
          acting under false pretenses. We expect that you will exercise caution
          when using the Website. You understand and agree that we do not
          guarantee the accuracy or legitimacy of any listings, leads, postings,
          or information by other users. You further agree that we are not
          liable for any loss of money, goodwill, or reputation, or any special,
          indirect, or consequential damages arising out of your use of the
          Website or as a result of any sale or purchase of goods and services
          with other users of the Website. Grow Infinity Realtors is not liable
          in any manner to any third party/User for any content/listing posted
          by the Users on the Website. Grow Infinity Realtors reserves the
          right, consistent with reasonable commercial business practices, to
          remove all or any part of the properties and/or other goods and
          services posted on any part of the Website without prior notice.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Link To Third Party Sites
        </h2>
        <p className="mb-6 text-justify">
          The Website may provide links to websites and access to content,
          products, and services from third parties, including users,
          advertisers, affiliates, and sponsors of the Website. You agree that
          Grow Infinity Realtors is not responsible for the availability or
          accuracy of content including, but not limited to, opinions, advice,
          statements, and advertisements provided on third-party websites, and
          you shall bear all risks associated with the use of such content and
          for acting upon such content. You are requested to review the policies
          posted by respective websites regarding privacy policy and terms of
          use before using said third-party websites. Grow Infinity Realtors is
          not responsible for any loss or damage of any sort you may incur from
          using the content of third-party websites. Grow Infinity Realtors
          makes no representations or warranties as to the functioning of any
          third-party website. A link to a third-party website from the Website
          does not constitute endorsement by Grow Infinity Realtors of the owner
          of the other site, the content of its site, or its products or
          services.
        </p>

        <h2 className="text-2xl font-semibold mt-8 text-gray-900 border-b pb-2">
          Governing Law & Jurisdiction
        </h2>
        <p className="mb-6 text-justify">
          By accessing the Website, you agree that the laws prevailing in India
          shall govern all matters relating to these Terms.Courts in India alone
          shall have exclusive jurisdiction in all matters relating to the use
          of these Terms, irrespective of the territory and jurisdiction of your
          access to the Website. You agree to inform us if you come across any
          listing or posting that is offensive or violates our listing policy or
          infringes any intellectual property rights by sending an email to
          ankitgoyal@growinfinityrealtors.in to enable us to keep the Website
          functioning efficiently and safely. We reserve the right to take down
          any posting, listing, or information and/or limit or terminate our
          Services while taking all reasonable technical and legal steps to
          prevent the misuse of the Website in keeping with the letter and
          spirit of these Terms. In the event you encounter any problems with
          the use of our Website or Services, you are requested to report the
          problem by sending an email to ankitgoyal@growinfinityrealtors.in. The
          information provided on this Website is based on Grow Infinity
          Realtors data, which is collected from various publicly known sources,
          such as websites, documents, and maps, including Grow Infinity
          Realtors’s proprietary data resources, and from the inputs of
          unidentified individuals. It should be considered as a guideline and
          not as absolutely certain. While care has been taken, no
          responsibility is accepted for the accuracy of the whole or any part.
          The information herein should not be reproduced in any form, in part
          or whole, without prior written permission from Grow Infinity
          Realtors. The information is provided on an “as is” and “as available”
          basis. Grow Infinity Realtors expressly disclaims any warranties of
          any kind, whether express or implied, including, but not limited to,
          the implied warranties of merchantability, fitness for a particular
          purpose, and non-infringement.
        </p>
      </div>
    </Layout>
  );
};
